    location / {
        try_files $uri @php;
    }

    location @php {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param DOCUMENT_ROOT $document_root;
        include fastcgi_params;
        fastcgi_param PHP_VALUE "error_log=/var/log/nginx/repman_php_errors.log";
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg)$ {
        root /app/public;
        try_files $uri =404;
    }
